[build]
  command = "npm install && npm run build"
  functions = "dist" #  netlify-lambda reads this
  environment = { NODE_VERSION = "8.9.3" }

[[redirects]]
  from = "/"
  to = ".netlify/functions/gogonow/"

[[redirects]]
  from = "/schedule"
  to = ".netlify/functions/gogonow/schedule"

[[redirects]]
  from = "/weather"
  to = ".netlify/functions/gogonow/weather"
