//USERS
export const USER_LOGIN = 'USER_LOGIN';
export const USER_AUTH = 'USER_AUTH';
export const USER_GET_DATA = 'USER_GET_DATA';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_LOADING = 'USER_LOADING';

//SCHEDULES
export const SCHEDULES_GET = 'SCHEDULES_GET';
export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
