//USERS
export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const USERS_LOADING = 'USERS_LOADING';

//SCHEDULES
export const GET_SCHEDULES = 'GET_SCHEDULES';
export const SCHEDULE_LOADING = 'SCHEDULE_LOADING';
